/**
 * Word lists of the local token generator (§5). Plain ASCII, one word each, 12 characters at
 * most, so any `<Adjective> <Noun>` fits the 32 bytes of a name and any ticker built from them
 * is A to Z. Nothing here is interface text: en.ts holds the screens, this file holds the
 * tokens.
 *
 * Content rules (§5, §10.4): no brand, no protected character, nothing offensive, and no
 * promise of gain or financial advice. `words.test.ts` checks the last one with a blacklist.
 */

export const ADJECTIVES = [
  "Amber",
  "Arctic",
  "Astral",
  "Autumn",
  "Blazing",
  "Boreal",
  "Bouncy",
  "Brave",
  "Breezy",
  "Bubbly",
  "Candy",
  "Cheeky",
  "Chilly",
  "Clever",
  "Cloudy",
  "Cobalt",
  "Coral",
  "Cosmic",
  "Cranky",
  "Crimson",
  "Crispy",
  "Curious",
  "Dapper",
  "Daring",
  "Dizzy",
  "Dreamy",
  "Dusty",
  "Electric",
  "Ember",
  "Emerald",
  "Fancy",
  "Feisty",
  "Floppy",
  "Fluffy",
  "Foggy",
  "Frosty",
  "Frozen",
  "Funky",
  "Fuzzy",
  "Galactic",
  "Gentle",
  "Giant",
  "Giddy",
  "Glowing",
  "Golden",
  "Groovy",
  "Grumpy",
  "Happy",
  "Hazel",
  "Honey",
  "Humble",
  "Hungry",
  "Icy",
  "Indigo",
  "Jade",
  "Jazzy",
  "Jolly",
  "Jumpy",
  "Lazy",
  "Leafy",
  "Loopy",
  "Lucky",
  "Lunar",
  "Magic",
  "Mango",
  "Marble",
  "Mellow",
  "Mighty",
  "Minty",
  "Misty",
  "Moon",
  "Mystic",
  "Neon",
  "Nimble",
  "Noisy",
  "Olive",
  "Orbital",
  "Peppy",
  "Perky",
  "Pixel",
  "Plucky",
  "Polite",
  "Puffy",
  "Quiet",
  "Quirky",
  "Rainy",
  "Retro",
  "Rocket",
  "Royal",
  "Ruby",
  "Rusty",
  "Salty",
  "Sandy",
  "Sassy",
  "Scarlet",
  "Shiny",
  "Silly",
  "Silver",
  "Sleepy",
  "Smoky",
  "Snappy",
  "Snowy",
  "Solar",
  "Sparkly",
  "Spicy",
  "Spooky",
  "Starry",
  "Stellar",
  "Stormy",
  "Sugary",
  "Sunny",
  "Swift",
  "Thunder",
  "Tidy",
  "Tiny",
  "Toasty",
  "Turbo",
  "Velvet",
  "Wild",
  "Witty",
  "Wobbly",
  "Wonky",
  "Yawning",
  "Zany",
  "Zesty",
  "Zippy",
] as const;

export const NOUNS = [
  "Acorn",
  "Alpaca",
  "Avocado",
  "Axolotl",
  "Badger",
  "Bagel",
  "Balloon",
  "Banana",
  "Bean",
  "Beaver",
  "Biscuit",
  "Bison",
  "Blanket",
  "Bucket",
  "Burrito",
  "Cactus",
  "Capybara",
  "Carrot",
  "Cherry",
  "Coconut",
  "Comet",
  "Cookie",
  "Crayon",
  "Cupcake",
  "Donkey",
  "Donut",
  "Dragon",
  "Duck",
  "Dumpling",
  "Falcon",
  "Ferret",
  "Flamingo",
  "Frog",
  "Gecko",
  "Gnome",
  "Goat",
  "Goblin",
  "Goose",
  "Hamster",
  "Hedgehog",
  "Hippo",
  "Iguana",
  "Jackal",
  "Jellyfish",
  "Kettle",
  "Kite",
  "Kitten",
  "Kiwi",
  "Knight",
  "Koala",
  "Lantern",
  "Lemon",
  "Lemur",
  "Lizard",
  "Llama",
  "Lobster",
  "Manatee",
  "Marshmallow",
  "Meteor",
  "Mitten",
  "Mole",
  "Moose",
  "Muffin",
  "Narwhal",
  "Newt",
  "Ninja",
  "Noodle",
  "Nugget",
  "Ocelot",
  "Octopus",
  "Otter",
  "Owl",
  "Oyster",
  "Pancake",
  "Panda",
  "Parrot",
  "Peach",
  "Pear",
  "Pebble",
  "Pelican",
  "Penguin",
  "Phoenix",
  "Pickle",
  "Pigeon",
  "Pillow",
  "Pirate",
  "Planet",
  "Platypus",
  "Plum",
  "Pony",
  "Potato",
  "Pretzel",
  "Pudding",
  "Puffin",
  "Pumpkin",
  "Quokka",
  "Rabbit",
  "Raccoon",
  "Radish",
  "Robin",
  "Robot",
  "Salmon",
  "Sardine",
  "Seal",
  "Shrimp",
  "Sloth",
  "Sock",
  "Sparrow",
  "Sprout",
  "Squid",
  "Taco",
  "Tadpole",
  "Tapir",
  "Teapot",
  "Toad",
  "Toaster",
  "Tomato",
  "Turtle",
  "Umbrella",
  "Unicorn",
  "Viking",
  "Waffle",
  "Walrus",
  "Weasel",
  "Wizard",
  "Wombat",
  "Yak",
  "Yeti",
  "Zebra",
] as const;

/** `An otter who <action>.` */
export const ACTIONS = [
  "loves the stars",
  "naps in the sun",
  "collects shiny pebbles",
  "dreams of the ocean",
  "dances in the rain",
  "hums old tunes",
  "chases butterflies",
  "sips tea at dawn",
  "hides snacks everywhere",
  "waves at strangers",
  "counts the clouds",
  "paints tiny rocks",
  "never skips breakfast",
  "hugs every tree",
  "rides a skateboard",
  "tells terrible jokes",
  "sleeps upside down",
  "juggles acorns",
  "whistles at night",
  "builds sandcastles",
  "reads by moonlight",
  "wears mismatched socks",
  "plants sunflowers",
  "bakes crooked cookies",
  "sings in the shower",
  "surfs the tide",
  "collects lost buttons",
  "talks to plants",
  "stargazes all night",
  "chews bubble gum",
  "skips stones",
  "knits little hats",
  "hoards rubber ducks",
  "climbs every hill",
  "howls at comets",
  "draws on foggy windows",
  "tap dances on tables",
  "follows rainbows",
  "steals the blanket",
  "guards the cookie jar",
] as const;

/** One short sentence each, punctuation at the end only: the sentence counter relies on it. */
export const TAGLINES = [
  "Born on a rainy Tuesday.",
  "Fueled by snacks and good vibes.",
  "Small paws, big heart.",
  "Certified nap champion.",
  "Always late, never sorry.",
  "Friends with every cloud.",
  "Runs on giggles.",
  "Made of stardust and crumbs.",
  "Best friend of the night sky.",
  "Allergic to boredom.",
  "Wears a cape on weekends.",
  "Has never lost a staring contest.",
  "Sleeps with one eye open.",
  "Collects hugs.",
  "Loud, proud and a little round.",
  "Powered by pure curiosity.",
  "Wobbles but never falls.",
  "Believes in second breakfast.",
  "Chaos with a cute face.",
  "Local legend, global snack.",
  "Zero plans, all heart.",
  "Smells faintly of cinnamon.",
  "Trusted by squirrels everywhere.",
  "Squeaks when surprised.",
  "Loves a good puddle.",
  "Keeps a map of every nap spot.",
  "Fluent in purrs.",
  "Keeper of the last cookie.",
  "Escaped from a bedtime story.",
  "Mostly harmless.",
] as const;
